#!/bin/bash
### BEGIN INIT INFO
# Provides:          rocs-svr
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start $autostart_app at boot time
# Description:       Enable service provided by $autostart_app.
### END INIT INFO

case "$1" in
  start)
    echo "Starting rocs-svr"
    cd /usr/local/bin/rocs-svr
    ./start_rocs_svr.sh&
    ;;
  stop)
    echo "Stopping rocs-svr"
    pkill -f /usr/local/bin/rocs-svr/start_rocs_svr.sh
    pkill -f rocs_svr
    ;;
  restart)
    echo "Restarting rocs-svr"
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit 0