version: "3.8"

volumes:
  controller_data:

services:
  webots:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEBOTS_DEFAULT_IMAGE=$IMAGE
        - PROJECT_PATH=$PROJECT_PATH
        - MAKE=$MAKE
    command: $WEBOTS
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=$XAUTHORITY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - '$PORT:$PORT'
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ${XAUTHORITY:-/dev/null}:${XAUTHORITY:-/dev/null}
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  controller:
    depends_on:
      - webots
    restart: unless-stopped # restarts the container if the simulation is reset
    build:
      context: .
      dockerfile: controller_Dockerfile
      args:
        - DEFAULT_CONTROLLER=$DEFAULT_CONTROLLER
        - PORT=$PORT
        - PROJECT_PATH=$PROJECT_PATH
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    tty: true # Allows the controller to send its output to Webots' console
    environment:
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WEBOTS_STDOUT_REDIRECT=1
      - WEBOTS_STDERR_REDIRECT=1
    volumes:
      - controller_data:$PROJECT_PATH/controllers/$DEFAULT_CONTROLLER:rw

  theia:
    image: benjamindeleze/theia-test:test3
    ports:
      - $THEIA_PORT:3000
    volumes:
      - controller_data:/home/project/webots-project:rw
