version: "3.8"

services:
  webots:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEBOTS_DEFAULT_IMAGE=$IMAGE
        - PROJECT_PATH=$PROJECT_PATH
        - MAKE=$MAKE
    command: $WEBOTS
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '$PORT:$PORT'
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - /dev/dri:/dev/dri:rw
