version: "3.8"

volumes:
  controller_data:

services:
  webots:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEBOTS_DEFAULT_IMAGE=$IMAGE
        - PROJECT_PATH=$PROJECT_PATH
        - MAKE=$MAKE
    command: $WEBOTS
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - '$PORT:$PORT'
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev/dri:/dev/dri:rw
      - controller_data:/usr/local/$THEIA_VOLUME:rw

  theia:
    image: benjamindeleze/theia-test:test3
    ports:
      - $THEIA_PORT:3000
    volumes:
      - controller_data:/home/project/webots-project:rw
